### ISSUE TITLE
Delve can't find source files when -gcflags=-trimpath is used

### ISSUE THREAD

**Issue by heschik** [derekparker/delve#1018]
1. What version of Delve are you using (`dlv version`)?
1.0.0-rc.2
2. What version of Go are you using? (`go version`)?
devel +a025277505 (tip as of today)

```
$ go build -gcflags=-trimpath=$(pwd) hello.go
```
The file name table for the CU:
```
$ readelf --debug-dump=info,line hello | grep -C 3 hello.go
 The File Name Table (offset 0x10fe1):
  Entry Dir     Time    Size    Name
  1     0       0       0       hello.go
  2     0       0       0       <autogenerated>
```
and the CU DIE:
```
 <0><5776e>: Abbrev Number: 1 (DW_TAG_compile_unit)
    <5776f>   DW_AT_name        : main
    <57774>   DW_AT_language    : 22    (Go)
    <57775>   DW_AT_stmt_list   : 0x10fc8
    <57779>   DW_AT_low_pc      : 0x482430
    <57781>   DW_AT_ranges      : 0x200
    <57785>   DW_AT_comp_dir    : /
    <57787>   DW_AT_producer    : Go cmd/compile devel +a025277505 Wed Nov 15 17:35:09 2017 +0000
```
I haven't looked at the code, but it seems that when Delve finds a relative path in the file name table, it prepends DW_AT_comp_dir. This is what the spec says to do, but in practice I don't think it would ever be useful given the way -trimpath works. At tip, _comp_dir is hardcoded to /, which won't work for any setting of -trimpath. In 1.9.2, _comp_dir is the PWD of the linker, so if you -trimpath $PWD as in the example it does happen to work in the common case. But if the linker is run in a temporary directory (as it is at Google) then you're out of luck.

 gdb seems to deal with this okay, maybe by just checking both with and without _comp_dir prepended. Given the above, maybe Delve should just ignore _comp_dir entirely?

CC @hyangah

**Comment by aarzilli** [comment]
Following the standard for _comp_dir is necessary to support cgo. However we could ignore it when it's "/" and DW_AT_language is "go".

I'm not at all opposed to doing this workaround but this seems more like a bug in the linker, even though it works with gdb. Maybe it should be fixed there since it's mostly new to 1.10 and 1.10 isn't released yet. Is there a particular reason that the linker is emitting "/" as DW_AT_comp_dir instead of omitting it entirely? Wouldn't "." be a better value for it?

**Comment by derekparker** [comment]
Thanks for looking into this issue @aarzilli, it was in the evening when I marked this and hadn't read through the supplied DWARF information thoroughly before labeling.

Delve is only following the spec, and as mentioned this is a new change in a yet unreleased version. This could potentially be marked a bug in Delve still if there is a strong reason for the linker behavior, however otherwise I agree with @aarzilli and feel this should be labeled an upstream issue.

It seems the behavior of `-trimpath` is essentially `gcc -g -fdebug-prefix-map=$(pwd)=. ...` using GCC.

**Comment by heschik** [comment]
> Wouldn't "." be a better value for it?

Probably. https://golang.org/cl/74790 doesn't seem to have spent much time considering the exact value. I can send a CL to change it and see how it goes.

We'll still need to make a Google-internal patch somewhere to get 1.9 to work, but that's not the end of the world; we should be able to just backport the linker change.

**Comment by heschik** [comment]
Okay, it's "." upstream now, and we backported it to our internal 1.9, so I'm happy. Closing.

**Comment by derekparker** [comment]
Perfect, thanks!

**Comment by zhangguanzhang** [comment]
same issue , when use `dlv attach` command not with code files

**Comment by zhangguanzhang** [comment]
@aarzilli PTAL
