### ISSUE TITLE
Internal compiler error during windows installation

### ISSUE THREAD

**Issue by fabcan** [derekparker/delve#1042]
While trying to install on windows, after launching the command `go get github.com/derekparker/delve/cmd/dlv` I get this error:

> \# github.com/derekparker/delve/vendor/golang.org/x/sys/windows
> <autogenerated>:1:0: internal compiler error: open $WORK\github.com\derekparker\
> delve\vendor\golang.org\x\sys\windows\_obj\go_asm.h: Access denied.

I've done it in Windows 8.1 Pro and go version `go1.9.2 windows/amd64`

**Comment by dlsniper** [comment]
I'm using Windows as well but I don't have this problem. Have you tried to remove delve from your system, ` rmdir $GOPATH/src/github.com/derekparker/delve `, and then run ` go get ` again? Is your destination properly writable? Do you have any antivirus running? What happens if you disable the antivirus?

**Comment by fabcan** [comment]
Hi, it seems that the antivirus is blocking some files due to their extension. I'll try to install it in another way
