### ISSUE TITLE
Add substitute-path support for remote debugging

### ISSUE THREAD

**Issue by ricardofandrade** [derekparker/delve#1163]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
1.0.0 
2. What version of Go are you using? (`go version`)?
1.9

3. What operating system and processor architecture are you using?
ubuntu trusty in a docker container running in osx

4. What did you do?
Set a breakpoint in GoLand for a binary built and run inside a Docker container.

5. What did you expect to see?
The breakpoint being set.

6. What did you see instead?
GoLand indicates an X marked breakpoint with the error "could not find <filename>"

More info:
* Local source path: `/home/user/source/test/test.go`
* Docker source path: `/test/test.go`
* GoLand version 2017.3.3 (March 5 build)

Other findings:
* By using Wireshark I could see that GoLand sends my local source path to delve.
* Internally, delve fails to find the file in `BinaryInfo.LineToPC()` returning the error seen in the GoLand.
* There's currently no way to make GoLand send the remote path (waiting on JetBrains to confirm).
* `--init <file>` does not work with remote debugging (`--headless`), so it's impossible to set a substitute path in delve for GoLand.

So this issue is to request a feature where either:
* A command line switch for informing substitute paths.
* Or an API for doing that.
* Or just make the contents of file passed in for `--init` to work with `--headless`.

**Comment by dlsniper** [comment]
Hi,

We have a ticket on the IDE side, https://youtrack.jetbrains.com/issue/GO-3988 for this.

I'm trying to identify the issue from above in this forum post https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000162444-Cannot-set-breakpoints-when-there-two-files-with-the-same 

This is probably because of the way that the IDE maps the source automatically, but unfortunately I need more details in order to investigate the issue, and the paths / steps above do not help me reproduce the issue.

I see that you are using 2017.3, can you please upgrade to 2017.3.3 and try again?

Since you reported this on the forum, I would say let's try and fix it there as this is not a delve problem, the IDE can / should solve it on its own.

Thank you.

**Comment by ricardofandrade** [comment]
I am actually using build 2017.3.3 (updated the info above). So no need to try again.
