### ISSUE TITLE
Meet error:Command failed: could not get floating point registers: input/output error

### ISSUE THREAD

**Issue by MbbCoder** [derekparker/delve#1197]
My Delve version is 1.0.0
My Go version is go 1.8.3 linux/amd64

When I use Delve to check the code , b(set the breakpoint) and c(continue) can work, but when I press next and Enter, or print or stack, here come the err:"Command failed: could not get floating point registers: input/output error". 

So what should I do to figure that out?

Thanks!

**Comment by aarzilli** [comment]
Apply this patch https://github.com/derekparker/delve/pull/1198 and see what the error looks like. What kernel are you using?

**Comment by derekparker** [comment]
@MbbCoder have you had a chance to try the patch that @aarzilli submitted?

**Comment by kylemeow** [comment]
Encountered the same issue, cannot view variables while remote debugging using `dlv debug`, even though the breakpoints work as normal.

**Comment by aarzilli** [comment]
@kylemeow have you tried the associated PR? Does it print anything?

**Comment by WMLHUST** [comment]
Hello, I got this error again. 
Delve version: 1.1.0
golang version: 1.8.3 linux/amd64 and 1.11.2 linux/amd64, both failed
Linux kernel: 2.6.32.43 
-----------
error msg: 
(dlv) args
Command failed: could not get floating point registers: error calling GETREGSET input/output error
(dlv) n
> main.main() ./main.go:8 (hits goroutine(1):1 total:1) (PC: 0x4ad012)
Command failed: could not get floating point registers: error calling GETREGSET input/output error

I modified "pkg/proc/native/ptrace_linux.go" with this commit
 https://github.com/aarzilli/delve/commit/757233fe815553520d76fd1717a280f055f60789
but didn't modify "pkg/proc/registers.go", because I didn't find the function modified in that commit.
Instead, I found a similar function in "pkg/proc/linutil/regs.go : AMD64XstateRead()" and modified it.
`if err := binary.Read(rdr, binary.LittleEndian, &regset.PtraceFpRegs); err != nil {
	// return err
	return fmt.Errorf("error reading legacy area: %v", err)
}`
Then, make build, make install. 

Is there any solution? 
Thanks !
