### ISSUE TITLE
Breakpoints on functions not getting hit / getting hit too many times

### ISSUE THREAD

**Issue by aarzilli** [derekparker/delve#170]
In the process of implementing the breakpoints file feature I have come across a bug where breakpoints sometimes do not get hit or get hit many more times than excepted (ie. one breakpoint gets hit immediately after calling Continue without the debugged program making any progress).

I wrote a test that reproduces this problem, it's on this branch: https://github.com/aarzilli/delve/tree/continue-bug (it's forked from master, you should be able to pull it if you want). It doesn't happen every time, you will have to run the test repeatedly.
Unfortunately I can not figure out why it happens, it's not hardware breakpoints, btw, I tried disabling them.

Environment is go1.4.2 on linux, as usual.

**Comment by derekparker** [comment]
So, here's what could be happening (although note I haven't dug in too deep yet):

I notice you're setting breakpoints directly on functions. A pure Go function is going to have a prologue that checks the stack size and allocates / copies if necessary. When that allocation is hit, it jumps back up to that prologue and checks again.

As an example of this (disassembled on OSX):

```
0000000000002000 <main.useless>:
    2000:	65 48 8b 0c 25 a0 08 	mov    %gs:0x8a0,%rcx
    2007:	00 00 
    2009:	48 8d 44 24 a0       	lea    -0x60(%rsp),%rax
    200e:	48 3b 41 10          	cmp    0x10(%rcx),%rax
    2012:	77 07                	ja     201b <main.useless+0x1b>
    2014:	e8 27 e9 01 00       	callq  20940 <runtime.morestack_noctxt>
    2019:	eb e5                	jmp    2000 <main.useless>
```

So that morestack dance is likely what is causing the multiple breakpoint issue. Ideally if we are setting a breakpoint on function entry, we should skip the prologue. This could be done by setting the breakpoint at the first line inside the function instead, or directly after the prologue, which could still be considered the "entrypoint" of the function if it needs to adjust the stack pointer after the prologue is finished.

**Comment by aarzilli** [comment]
You seem to be correct about runtime.morestack_noctxt being the cause for the multiple breakpoints. The PR fixes it.

The part about breakpoints not being hit sometimes remains however that seems to actually be connected to hardware breakpoints (I've run TestContinueMulti for 3 hours without errors with hw breakpoints disabled), but it's also much more rare compared to the multiple breakpoint hits.

**Comment by derekparker** [comment]
Fixed by https://github.com/derekparker/delve/commit/a0115e3a15d8a03b78fa23a5d74d1b92ea20b21c
