### ISSUE TITLE
trace and thread both alias to "t"

### ISSUE THREAD

**Issue by quarnster** [derekparker/delve#184]
Also what exactly is a "tracepoint"? :)

**Comment by derekparker** [comment]
Fixed by https://github.com/derekparker/delve/commit/e9b3a9eac13af44913bf0ad7fd50281a1925f5ef.

A tracepoint is similar to a breakpoint, however instead of stopping the world and bringing the Delve prompt up, it will just emit a notification that it hit that part of the program. Additionally, every time a tracepoint is hit the value of specified variables and a stacktrace of N depth may be printed as well.
