### ISSUE TITLE
IDE interfaces

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#22]
Hi @derekparker,

First of all, Thank you for this!

While I haven't played with it yet, I plan to do so this weekend.

If all things work good enough, I'd be interesting in integrating it with the [Go plugin for IntelliJ IDEA](https://github.com/go-lang-plugin-org/go-lang-idea-plugin).

As I haven't seen anything that could help out IDEs do the interfacing part so I'd like to ask if there's any plans for this. I could potentially help out by defining an HTTP interface for it and just pipe all the commands to the debugger via HTTP calls / JSON responses. A side effect of this, then it could allow creating web interfaces for this.

What do you think? Does it make sense to you? If you'd like to chat, please drop me a mention [on Gitter](https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin).

Kind regards

**Comment by grafov** [comment]
+1 for websockets. It is easy way for send messages from each side and easy to integrate with browsers to build webUI. I more interested with integration with GNU Emacs, it has libs for websockets support.

**Comment by jacque006** [comment]
+1 for this feature, would be very useful for developers where I work.

**Comment by ironcladlou** [comment]
@derekparker I just reviewed @dlsniper's [websockets branch](https://github.com/derekparker/delve/compare/master...dlsniper:add-websocket-support). Have you taken a look? What are the chances you'll eventually accept a PR based on the approach? It's not how I would have gone about the refactor, but it looks viable.

I ask because I was interested in starting to integrate delve with my own Sublime tooling, and am trying to decide where to most effectively spend my time (e.g. contributing to @dlsniper's branch, contributing to some other more acceptable branch you know of, starting my own client/server refactor, a stopgap interface to control the CLI directly, etc.)

Thanks for this tool!

**Comment by dlsniper** [comment]
I'll do the promised rebase this weekend as I finally have time for it, sorry for disappearing for a while.

**Comment by markturansky** [comment]
I volunteer to help test the IDEA plugin, as I'm using it already and would love to help improve it.  A working Go debugging in IDEA is nirvana.

**Comment by derekparker** [comment]
@ironcladlou I haven't taken a look recently, I've been polishing the OS X stuff and mucking around with the core. I'd like to take another look after the rebase has happened since there has been a lot of changes on master recently that may or may not affect this branch.

So to answer your question, I'm certainly open to more discussion around this, and if you were interested in working through a pure refactor I'd absolutely be open to that. There are no competing branches for this feature that I am aware of.

There are some high level refactors I would love to work on / accept PRs for, namely moving towards a client/server implementation with the _existing_ cli, i.e. dogfood first with what exists and build out from there, essentially making the CLI a client of the server, preventing it from using `proctl` directly, instead sending commands with arguments to a core server which actually handles process manipulation.

Then with that refactor done, this PR could be simply adding a new client to the core debug server, with a standard interface that has been defined via usage by the CLI. If you'd be interested in working on that ( @ironcladlou or anyone else) I'd happily help move it along and merge it, as currently I'm spending a majority of my time working on the guts of the thing.

@dlsniper thanks for your work on this and I will promptly take a look at the branch post-rebase.

**Comment by ironcladlou** [comment]
@derekparker @dlsniper 

So, for discussion I thought it'd be faster to just start a POC of the client/server separation I had in mind. Here's my WIP branch:

https://github.com/derekparker/delve/compare/master...ironcladlou:http-api?expand=1

What I've done there is:

* Started a public API in `api/types.go`. For now, and for simplicity's sake, this is unstable. Later, you could subpackage *public* types `api/v1beta1` or something, use `api/types.go` as the *internal* types, and convert to/from internal/external with registered API converters. This would allow IDE integrators to have stable versioned APIs on which to build tools, while allowing you the flexibility to advance the API internally and eventually mint new public versions while maintaining backwards compatibility.
  * For an example of this in practice, check out Google's [Kubernetes](https://github.com/GoogleCloudPlatform/kubernetes) or [OpenShift Origin](https://github.com/openshift/origin); I work on both and so I have this stuff on the brain lately.
* Built a `net/http` server in `proctl/server` on top of `proctl/DebuggedProcess`. This abstracts access to the debugging session. It's not yet websocket based.
* Defined a Go client interface in `client/client.go` which provides Go consumers with an interface to the server. The default implementation uses the `net/http` library to make server requests.
* Changed the responsibility of the `dlv` command to be:
  1. Start and attach to the process
  2. Spin up the server
  3. Instantiate a Go client to the server
  4. Create a CLI which uses the client to interface with the server (it also gets a pointer to the process for backwards compatibility to allow piecemeal replacement of commands)
* Decoupled the CLI (terminal) from the session bootstrapping; the CLI is now able to be incrementally converted to a pure Go client implementation

There's still a ton of work to do:

* Finish defining the API
* Finish implementing the server interface
* Convert the web server to a websockets implementation
* Abstract encoding/decoding
* Abstract server handling boilerplate
* Support public API versioning/conversion
* Godocs
* API documentation

Other random stuff that could be done:

* Take full advantage of websockets by implementing something like `syscall.Wait4` or something to allow client breakpoint notification subscriptions.

Have a look and let me know how you feel. If you like the direction, I'd be happy to work on it in my spare time.

**Comment by dlsniper** [comment]
@ironcladlou I've looked at the changes you've done and it looks interesting. The ideas you have for how to approach the API are good. However, before you can do that, I believe a separate refactoring of the internals should be done as currently none of the internal commands are returning the output but rather use ```fmt.Print*``` directly. I'd be happy to have a look every now and then over the progress but I can't do any sustainable effort to first to the internal changes then implement something on top of them.

**Comment by ironcladlou** [comment]
@dlsniper 
>However, before you can do that, I believe a separate refactoring of the internals should be done as currently none of the internal commands are returning the output but rather use fmt.Print* directly.

We might be having a terminology mismatch here. I already changed the command interface and two command implementations (breakpoints and threads) to use the new API client. I think some confusion is coming from the mixed terms at play here.

I have other ideas for how the CLI should be refactored to draw better distinctions (e.g. daemonized server mode, interactive client mode, foreground server/interactive client), but I'd rather discuss those in a PR.

**Comment by ironcladlou** [comment]
Moving the discussion to #88 to keep this thread clean.

**Comment by ldornin** [comment]
+1, and I'd like to add Idea is the only real IDE... period.

**Comment by dlsniper** [comment]
with #88 being closed, I think I can close this one as well. If not, please feel free to reopen this.
