### ISSUE TITLE
Continue command doesn't work in certain situations

### ISSUE THREAD

**Issue by ignatov** [derekparker/delve#262]
```go
package main
import "fmt"

func typicalFunction() (res int) {
	defer func() {
		res = 2
		return
	}()
	res = 10
	return // setup breakpoint here
}

func main() {
	fmt.Println(typicalFunction())
}
```
Delve revision: af16cfa90b04ffda668dfd98d73247d2e9499a2d

```
> main.typicalFunction() ./defer.go:10

    5:		defer func() {
    6:			res = 2
    7:			return
    8:		}()
    9:		res = 10
=> 10:		return
   11:	}
   12:
   13:	func main() {
   14:		fmt.Println(typicalFunction())

(dlv) c
> main.typicalFunction() ./defer.go:10

    5:		defer func() {
    6:			res = 2
    7:			return
    8:		}()
    9:		res = 10
=> 10:		return
   11:	}
   12:
   13:	func main() {
   14:		fmt.Println(typicalFunction())
```

**Comment by aarzilli** [comment]
Are you sure this happens on that revision? Because I can only reproduce this on my [fix-247 branch](https://github.com/aarzilli/delve/tree/fix-247). I have fixed it there but I can't think of a reason why this behaviour would happen on master.

**Comment by ignatov** [comment]
The same on f2e5214e1b5c on Mac OS X 10.11 El Capitan.

**Comment by derekparker** [comment]
I was just able to reproduce this on master.

**Comment by aarzilli** [comment]
A couple of weeks ago I managed to get an OS X VM working so today I thought I would take a look at this bug.
It turns out that the problem is very similar to my own fuckup in PR #259: `proc.(*Thread).singleStep` calls `t.dbp.trapWait`, and trapWait thinks we hit the breakpoint instead of stepping through a `NOP` instruction, since `NOP` (which is the instruction the breakpoint in question is set to) is one byte long, just like `INT 3`.

One possible solution is to call `mach_port_wait` directly, initially I did this:
```
C.mach_port_wait(C.mach_port_t(t.os.thread_ct))
``` 
thinking it would wait for a single thread, but it didn't work (I only have a vague idea of how this things work). Calling `C.mach_port_wait(t.dbp.os.portSet)` instead works, but my opinion is that waiting for just the specific thread would be better.

Another option is to add an 'enabled' flag to breakpoints and temporarily set it to false when we are stepping over them, then `trapWait` would know that the breakpoint wasn't hit.

**Comment by derekparker** [comment]
@aarzilli calling `C.mach_port_wait(t.dbp.os.portSet)` is actually correct in this context. The `portSet` contains the exception port, which is what we need to wait on, not the port of the thread itself.

**Comment by dlsniper** [comment]
Hi,

I'm currently running into this issue as well but on Ubuntu.

Here are my details:

```
go get github.com/dlsniper/test
go build -o /tmp/demo0go -gcflags "-N -l" github.com/dlsniper/test
dlv exec /tmp/demo0go

b main.go:20
c
c
Command failed: could not continue thread <#ThreadID> no such process
(dlv) q
process must be stopped in order to kill it

go version 
go version go1.5.2 linux/amd64

uname -a
Linux sniper 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```

From my observation, I could see the process starting in `Suspended` state, then when the process stopped at the breakpoint it was correctly in `Trace`. After the breakpoint continued, the process then remained in `Zombie` state (which means waiting for parent to read the exit code).
With this information I've done the experiment again and I've realized that the error that Delve throws, `Command failed: could not continue thread <#ThreadID> no such process` is stating the `<#ThreadID>` correct but since the thread is in zombie state as the main program exited, this means that somehow Delve doesn't process the exit signal from the app after resuming from the breakpoint.
As such, by removing the comment on line 22, the bug doesn't happen anymore, because I guess delve has more time to process the OS signal after resuming from the previous state.

I can consistently reproduce this, please let me know if you need any further details or help with this.
