### ISSUE TITLE
JSON-RCP: Variable type

### ISSUE THREAD

**Issue by ignatov** [derekparker/delve#293]
I'm using JSON-RCP and for some struct variables I've got a type with prefix, e.g. `struct runtime.g`, for other without it – `main.mytype`. Which is correct? With `struct ` prefix or not?

**Comment by derekparker** [comment]
@aarzilli for this output, we should display the GoType instead of the dwarf type. We've discussed this before but remember there is the GoType info embedded in the Dwarf info, but only golang.org/x/dwarf is parsing it and stdlib is not? Ideally we use the actual Go type for everything external and only use dwarf types internally when necessary.

**Comment by derekparker** [comment]
@aarzilli seems like https://github.com/derekparker/delve/pull/362 should help clear this up?

**Comment by aarzilli** [comment]
Yes.

**Comment by derekparker** [comment]
Fixed as of https://github.com/derekparker/delve/pull/362.
