### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by uuf6429** [derekparker/delve#371]
I'm building delve on Windows (10 Pro 64bit) on a 2nd machine (the first one worked perfectly).

I'm getting this error message when I run `mingw32-make install`:

> process_begin: CreateProcess(NULL, uname, ...) failed.
> process_begin: CreateProcess(NULL, uname, ...) failed.
> go install -ldflags="-X main.Build=1bda586115ad3ca0daa6f5b7180a6bc662c72685" github.com/derekparker/delve/cmd/dlv
> \# github.com/derekparker/delve/proc
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> Makefile:44: recipe for target 'install' failed
> mingw32-make: *** [install] Error 2

The makefile itself calls uname directly and unconditionally:
https://github.com/derekparker/delve/blob/master/Makefile#L2

Of course, command `uname` is not available on Windows, so I'm actually surprised this worked on my first machine.

**Comment by jussij** [comment]
>  I'm actually surprised this worked on my first machine.

Just a few hours ago I ran into build issues, that turned out to be nothing but user error.

The details of that experience are described here: https://github.com/derekparker/delve/issues/369

As someone who works a lot on Windows, one of the issues with Windows is no two Windows machines are the same and as such there are lots of these types of issues.

But the fact you have one Windows 10 machine that did build Delve and I too can confirm I was able to build Delve just fine on a Windows 10 Pro x64 machine, that suggest to me this is probably not a Delve bug, but rather a bug related to that particular Windows machine and it's installation.

**Comment by uuf6429** [comment]
I've been able to compile now, but I needed to have the `uname.bat` hack. I suspect it is only being used to discriminate against OSX (Darwin) and hence why it didn't break anything else.

**Comment by vornet** [comment]
The easiest way for me to get it to work is to install tdm64-gcc-5.1.0-2.exe from http://tdm-gcc.tdragon.net/download and run:

go get -v -u github.com/peterh/liner github.com/derekparker/delve/cmd/dlv

**Comment by derekparker** [comment]
Seems resolved so I will close. I am open to Makefile improvements as well.

@vornet, you shouldn't have to install `liner` explicitly, it should be vendored.
