### ISSUE TITLE
Step Command Hangs

### ISSUE THREAD

**Issue by jussij** [derekparker/delve#372]
On Windows I am able to hang the debugger using the step command as described below.

1) Start the debugger:

    C:\Go\src\github.com\jussij\DelveTest>dlv.exe debug main.go
    Type 'help' for list of commands.

2) Issue the step command:

    (dlv) step

At that point the debugger hangs.

But I I continue to wait for a few minutes the debugger does return with this output:

    C:\Go\src\github.com\jussij\DelveTest>dlv.exe debug main.go
    Type 'help' for list of commands.
    (dlv) step
    Sending #0 message with body: Golang Weekly Newsletter #756 by John Smith
    Sending #1 message with body: Golang Weekly Newsletter #756 by John Smith
    Sending #2 message with body: Golang Weekly Newsletter #756 by John Smith
    Process 1092 has exited with status 0
    (dlv)

If instead I issue the continue command rather than the step command, the response is instantaneous as shown below:

    C:\Go\src\github.com\jussij\DelveTest>dlv.exe debug main.go
    Type 'help' for list of commands.
    (dlv) continue
    Sending #0 message with body: Golang Weekly Newsletter #756 by John Smith
    Sending #1 message with body: Golang Weekly Newsletter #756 by John Smith
    Sending #2 message with body: Golang Weekly Newsletter #756 by John Smith
    Process 32156 has exited with status 0
    (dlv)

**Comment by aarzilli** [comment]
Since you did not set any breakpoint the `continue` behaviour is obviously correct.

`step` will single step the current thread until it reaches a different source line, the thread you are on after attaching to the process is probably a system thread that never gets to any source line so `step` will just take you out of the process, just more slowly, since it's single stepping the thread.

There isn't anything really wrong with this. If you want to step through the program set a breakpoint `break main.main` and then `continue`.

**Comment by jussij** [comment]
>  just more slowly, since it's single stepping the thread.

I have a top end machine with lots of ram and plenty of hertz to burn.

Running that single step command took 50 'cats and dogs' (about 50 seconds) before I got any any feedback that anything was happening, and I was only debugging a 10 line Go program.

I actually only noticed this because I was typing in the bug report ;) 

If it had not been for that I would have killed the debugger long before, since for 50 seconds there was no user feedback and it looked like it had hung.

By comparison, if you do the same thing in Visual Studio the debugger will start and even if you do or don't break points in place, it will always stop on the main entry point.

**Comment by aarzilli** [comment]
> I have a top end machine with lots of ram and plenty of hertz to burn.
>
> Running that single step command took 50 'cats and dogs' (about 50 seconds) before I got any any feedback that anything was happening

You are underestimating how much code needs to run in the kernel to get through a small program one instruction at a time.

> By comparison, if you do the same thing in Visual Studio the debugger will start and even if you do or don't break points in place, it will always stop on the main entry point.

Automatically continuing until `main.main` was something that was considered, it wasn't done because `main.main` isn't the entry point for a go program and the user could be interested in debugging a package's `init` function.

Maybe we could normally continue until `main.main` but have a command line flag to disable this behaviour.

**Comment by derekparker** [comment]
Going to close this as it is not necessarily a bug, as @aarzilli mentioned.

Also, this problems exists for the reasons that were mentioned as well. I've created https://github.com/derekparker/delve/issues/374 to track the issue of a more user friendly startup procedure.
