### ISSUE TITLE
Printing a variable causes: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by britannic** [derekparker/delve#406]
Mac OS X 10.11.3
Code that causes panic: [Go Playground](https://play.golang.org/p/qnvETiq85g)
go version go1.6rc2 darwin/amd64

Delve Debugger
Version: 0.11.0-alpha
Build: 06bba9b7a9ad0e06f4d74bf71f7667d24872a838

To reproduce: 

1. set breakpoint: b cfg_parser.go:146
2. Print variable: p cfgtree

Output and stack trace attached
[delve_panic.txt](https://github.com/derekparker/delve/files/120317/delve_panic.txt)

**Comment by derekparker** [comment]
Thanks for reporting this bug! Next time if you could upload gists instead that would be a lot easier to take a look at the provided examples (the playground is better for smaller, runnable examples).

@aarzilli seems the code path that is panic-ing assumes that `Variable` will have a child, since it's in the `unsafe.Pointer` branch of the switch. Is there any reason off the top of your head an unsafe.Pointer variable type would not have a child representing the derefed value? Possibly it hasn't actually been eval'ed or properly derefed beforehand?

**Comment by britannic** [comment]
Will do! Appreciate the quick follow up. Delve is an awesome contribution, thanks very much.

**Comment by britannic** [comment]
Despite the panic, I was still able to find the bug with Delve, really saved some time.

**Comment by aarzilli** [comment]
I'll debug this tomorrow.
