### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by epipho** [derekparker/delve#43]
Tests are failing on master and I have not yet found a cause.

```
new thread spawned 1476
new thread spawned 1477
new thread spawned 1487
new thread spawned 1488
Hello, World!
new thread spawned 1497
new thread spawned 1498
new thread spawned 1508
new thread spawned 1534
new thread spawned 1535
new thread spawned 1536
foo
Hello, World!
foo
foo
Hello, World!
new thread spawned 1545
new thread spawned 1555
new thread spawned 1556
new thread spawned 1565
--- FAIL: TestVariableFunctionScoping (1.22s)
        proctl_test.go:52: Continue() returned an error : could not get registers could not get registers no such process
new thread spawned 1580
new thread spawned 1581
FAIL
FAIL    github.com/derekparker/delve/proctl     10.588s
```

**Comment by derekparker** [comment]
Yeah, it seems to be a flickering failure but it's definitely there. I'll look into it, I may have an idea why this is happening.

**Comment by derekparker** [comment]
So, for some reason on my laptop (Debian Jessie running kernel 3.17) the tests pass fine 99% of the time, with occasional, but rare flickers. However, on an Ubuntu 14.10 vm I have the tests always seem to fail consistently on master.

I'm going to investigate this more and try and figure out what is causing master to fail on certain machines, and under what circumstances.

**Comment by epipho** [comment]
It seems to always fail on both VMs for me (Ubuntu 14.04 and CoreOS 561)

**Comment by derekparker** [comment]
So, on the ubuntu VM that reproducibly fails, I have `TestNext` and `TestVariableFunctionScoping` failing consistently. I have tracked down why `TestNext` is failing, it's due to `m.procid` not being set correctly for a newly created thread. No idea why this is happening, I'm running go 1.4.1 on both my actual machine and on the VM and the VM fails whereas on my machine all tests pass with no problem.

Haven't dug into the `TestVariableFunctionScoping` failure yet, but it could be related.

**Comment by pnasrat** [comment]
I just tried on GCE on Operating System: CoreOS 575.0.0

@epipho what are you using as a host VM?
