### ISSUE TITLE
Suggest Makefile codesign should use $GOBIN not $GOPATH/bin 

### ISSUE THREAD

**Issue by kkdai** [derekparker/delve#502]
1. What version of Delve are you using (`dlv version`)?
0.11.0-alpha

2. What version of Go are you using? (`go version`)?
go1.6 darwin/amd64

3. What operating system and processor architecture are you using?
Mac OSX 10.11.4

4. What did you do?
run `GO15VENDOREXPERIMENT=1 CERT=dlv-cert make install`

5. What did you expect to see?
work with no error.

6. What did you see instead?
`No such file or directory`

Because Makefile use 

line 46: `codesign -s "$(CERT)" $(GOPATH)/bin/dlv`

But according to go document define about [Environment variables](https://golang.org/cmd/go/) 

```
GOBIN
	The directory where 'go install' will install a command.
```

Because `Makefile` use `go install $(BUILD_FLAGS) github.com/derekparker/delve/cmd/dlv` to install dlv. we should use `$GOBIN` path for codesign.

This issue will happen to all whom use homebrew for Golang installation will occur the same error during codesign delve.

Any advice is welcome, thanks.

**Comment by derekparker** [comment]
Thanks for filing an issue. My concern here is that we cannot rely on `$GOBIN` having been set by the user, since it's not required in the same way that `$GOPATH` is. I think the way to fix this issue is to do something like: `codesign -s "$(CERT)" $(which dlv)`. This obviously relies on `which` being available on the users machine, but it should be present on OSX machines.

**Comment by kkdai** [comment]
Thank you for your reply, I agree it would be better to change to `$(which dlv)`.
