### ISSUE TITLE
Cannot run delve against CLI app

### ISSUE THREAD

**Issue by JonathanRosado** [derekparker/delve#533]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 0.11.0-alpha
Build: 
```
2. What version of Go are you using? (`go version`)?
```
go version go1.5.4 linux/amd64
```
3. What operating system and processor architecture are you using?
Ubuntu 14.04
4. What did you do?
`dlv exec ./executable "--some-flag value"`
5. What did you expect to see?
Expected for delve to run precompiled binary with flags/arguments
6. What did you see instead?
`Error: unknown flag: --some-flag value`

**Comment by cbisnett** [comment]
It looks like the issue here is that Delve is trying to interpret the arguments you intended for the debugged application. You need to separate the arguments to the application from arguments to Delve itself. Try adding `--` after any arguments to Delve but before the arguments to the debugged application. So  your command line would become `dlv exec ./executable -- --some-flag value`

**Comment by JonathanRosado** [comment]
@cbisnett Thanks!
