### ISSUE TITLE
Strings cut during debugging

### ISSUE THREAD

**Issue by b5y** [derekparker/delve#659]
1. What version of Delve are you using (`dlv version`)? 
0.11.288

2. What version of Go are you using? (`go version`)? 
1.7.3

3. What operating system and processor architecture are you using?
Software:

System Software Overview:

System Version: macOS 10.12 (16A323)
Kernel Version: Darwin 16.0.0

Processor: 2,4 GHz Intel Core 2 Duo

4. What did you do? Concatenate strings

5. What did you expect to see? Proper result of long string

6. What did you see instead? Cutting resulted string

This is my code:
```go
package main

import (
	"os"
	"fmt"
)

func main() {
	fileName := os.Args[1]
	fmt.Println(fileName)
	cmd := fmt.Sprintf("%v%v%v", "file ", fileName, " -I")
	fmt.Println(cmd)
}
```

And this is screenshots of debugging process:

![screen shot 2016-10-28 at 11 39 02](https://cloud.githubusercontent.com/assets/1110987/19801194/d9d0b10e-9d06-11e6-90e3-9fa897db33af.png)
![screen shot 2016-10-28 at 11 39 12](https://cloud.githubusercontent.com/assets/1110987/19801196/d9d1bbb2-9d06-11e6-87b9-4a0cbc302dfb.png)
![screen shot 2016-10-28 at 11 39 21](https://cloud.githubusercontent.com/assets/1110987/19801195/d9d182c8-9d06-11e6-8c0f-f41f37176dd5.png)
![screen shot 2016-10-28 at 11 39 29](https://cloud.githubusercontent.com/assets/1110987/19801197/d9d5f75e-9d06-11e6-8bb5-5d820f0fb64f.png)

Similar issue was created on golang plugin repository for IDEA platforms:
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2811

*NOTE:* Everything is fine when I send short strings.

**Comment by aarzilli** [comment]
This is by design (alternatively: the bug is in the plugin, not in delve). When clients request an expression evaluation from the server they have the option to specify the maximum length that we should read from a string.

The default for maximum string length is 64, we picked this value so that variables would fit into a small terminal window, other clients should pick a value that suits them.

By comparing the length of the Value field and the Len field it's possible to determine if the string was fully loaded or not. This is also a thing delve clients should do and signal truncated strings to the user, the default client does it.
