### ISSUE TITLE
on ubuntu installing by go get does ot work at all 

### ISSUE THREAD

**Issue by NikosEfthias** [derekparker/delve#688]
1. What version of Delve are you using (`dlv version`)?
```bash
Delve Debugger
Version: 0.11.0-alpha
Build: 
```
2. What version of Go are you using? (`go version`)?
`go version go1.7.4 linux/amd64`
3. What operating system and processor architecture are you using?
`Linux nikosPC 4.8.0-32-generic #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
4. What did you do?
`dlv debug main.go`
5. What did you expect to see?
when i type `n` and hit enter program to continue untill break point and `ls` to list files of project
6. What did you see instead?
`n` does following ![](http://i.imgur.com/jG2DCuW.png)

and `ls` results 
```bash
Stopped at: 0x7f47e29c6ca0
=>no source available
```
here is my main.go file

```go
package main

import (
	"log"
	"net/http"
	"os"

	"path/filepath"

	"sgin/views/routes"
	"sgin/views/routes/user"

	"sgin/api"

	"github.com/pressly/chi"
	"github.com/pressly/chi/middleware"
)

func main() {
	app := chi.NewRouter()
	app.Use(middleware.RealIP, middleware.Logger /*middleWares.RedirectUnAuthorized*/)
	cwd, _ := os.Getwd()
	var port = os.Getenv("PORT")
	if port == "" {
		log.Fatalln("no port env variable set")
	}
	app.Mount("/", routes.BasePath())
	app.Mount("/user",user.BasePath())
	app.Mount("/api/user", api.UserRoutes())
	app.FileServer("/public/", http.Dir(filepath.Join(cwd, "public")))
	log.Printf("App is listening on port %s\n",port)
	http.ListenAndServe(":"+port, app)
}
```

**Comment by aarzilli** [comment]
1. the argument for `dlv debug` is a package path not a file name
2. line 15 of your main.go is inside the import directive, can't break there, since your main function is also less than 15 lines I'm not sure what you are trying to accomplish
3. to set a breakpoint on main: `break main.main`.
4. `next` doesn't work immediately after the program is started, you need to use `continue` to hit the first breakpoint
