### ISSUE TITLE
Unable to print local variables

### ISSUE THREAD

**Issue by saleemjaffer** [derekparker/delve#811]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 0.12.2
Build: v0.12.2

```

2. What version of Go are you using? (`go version`)?
`go version devel +0716fef Mon Dec 12 01:31:50 2016 +0000 darwin/amd64`

3. What operating system and processor architecture are you using?
`OSX, darwin/amd64`

4. What did you do?
- Created an executable using `go install`.
- `dlv exex [binary name]`
- Set breakpoint using `b file.go:22`
- Did `n` a few lines after a local variable `x` was initialized
- Tried printing `x` using `p x`

5. What did you expect to see?
`The value of the local variable`

6. What did you see instead?
`Command failed: could not find symbol value for x`

**Comment by aarzilli** [comment]
You are not seeing the value of some local variables because the compiler is optimizing them away. 
You should use `dlv debug` or `dlv test` to compile your code. If you build the executable yourself you should pass the option `-gcflags='-N -l'` to the compiler.

If you used delve to compile or remembered to use `-gcflags='-N -l'` and the missing local variables are in a package other than main you may be victim of [this go bug](https://github.com/golang/go/issues/19340). If this is the case your only option is to manually purge the offending packages from `$GOPATH/pkg/`.

**Comment by dlsniper** [comment]
For Go 1.10+ you need to run ` -gcflags="all=-N -l" ` to have a better debug experience.

**Comment by dreamerlzl** [comment]
It could also be the case that the version of delve is far behind the Golang used to compile the binary.
