### ISSUE TITLE
breakpoints inside multi-line var declaration are unsafe

### ISSUE THREAD

**Issue by ivarg** [derekparker/delve#83]
It is possible to set a breakpoint in a multi-line variable declaration, at which point the variables have not yet been initialized. Calling `info locals` at that point will render undefined behavior and may result in a panic.

**Comment by derekparker** [comment]
Sure enough, thanks for reporting this.

@epipho would you have any interest in looking into this? You've taken an interest in the variable evaluation side of things and had some great commits. If not, I'll start digging into it.

**Comment by epipho** [comment]
I have run into this before.

The bad news is I am not sure what we can do about it as I don't think there is any information in the binary.

 Instead of a location expression for the variable location I would expect a location list (http://www.dwarfstd.org/doc/dwarf-2.0.0.pdf section 2.4.6) that would give a set of instruction ranges that the variable is valid for but the binary does not contain a .debug_loc section.

The same problem exists for code that shadows variables
```
func main() {
   f := "foo"
   {
     f := "bar"
     fmt.Println(f)
   }
   fmt.Println(f)
}
```
This actually generates two variables, and there does not appear to be any way to disambiguate them.
```
<2><40>: Abbrev Number: 4 (DW_TAG_variable)
    <41>   DW_AT_name        : abcde
    <47>   DW_AT_location    : 5 byte block: 9c 11 a8 7f 22     (DW_OP_call_frame_cfa; DW_OP_consts: -88; DW_OP_plus)
    <4d>   DW_AT_type        : <0x2939f>
 <2><55>: Abbrev Number: 4 (DW_TAG_variable)
    <56>   DW_AT_name        : abcde
    <5c>   DW_AT_location    : 5 byte block: 9c 11 b8 7f 22     (DW_OP_call_frame_cfa; DW_OP_consts: -72; DW_OP_plus)
    <62>   DW_AT_type        : <0x2939f>
```
Thoughts?

**Comment by derekparker** [comment]
@epipho that's unfortunate. I don't see a clear fix other than patching the linker(s) to emit the `.debug_loc` section, or at the very least submitting an issue to the Go project to include that information.

**Comment by epipho** [comment]
This weekend I will dig through the go issue tracker to see if this has been brought up. I wonder what the complexity of the change would be to add .debug_log to the linker.

**Comment by derekparker** [comment]
@epipho not sure, but I know there's a lot going on with the compiler / linker rewrites. I'll likely post something on golang-dev about this and another Dwarf tag I'd like the linker to emit in the .debug_info section.

A cursory glance through the issue tracker didn't reveal any existing issues surrounding this, but if you dive deeper and find anything definitely let me know.

**Comment by epipho** [comment]
Which additional tags are you hoping for? For our purposes it might be nice
to have DW_TAG_lexical_block set so we can play nicer with scoping / autos.

**Comment by ivarg** [comment]
I don't know if this is related, but after continued testing I get erratic behavior similar to what I reported above, but also on completely valid source lines. For example, breaking in the following function at `fmt.Println(a1,a2)` and inspecting locals will list only uninitialized `a1`, i.e. `a1` with seemingly random size, len, and content.

```
func foo() {
	var (
		a1 = []int{1}
		a2 = 2
	)

	//println("")
	fmt.Println(a1, a2)
}
```

However, by uncommenting the `println("")` statement, locals will list expected values for both `a1` and `a2`.

**Comment by ivarg** [comment]
Btw, I get identical behavior in the above example on both darwin and linux (vbox image).

**Comment by derekparker** [comment]
@epipho DW_OP_form_tls_address would be nice for getting at the G(oroutine) in thread local storage, since `m->procid` can be unreliable and it can be difficult to map a scheduler M to a real OS thread.

@ivarg that's interesting... I'll try and play around with that example and check out the asm / debug info it generates, may be clues there. Not sure why a1 would be uninitialized in that example without that erroneous println call.

**Comment by ivarg** [comment]
Turns out I forgot to build with optimizations disabled. Building with `-gcflags "-N"` makes this second behavior go away. Sorry for that. Original issue is still valid though.

**Comment by derekparker** [comment]
@ivarg no worries, that makes sense. I'll still look into it a bit to see how feasible it would be for Delve to handle programs built without -N.

FWIW `dlv run` builds with `-gcflags="-N -l"`. Are you building manually and pointing Delve to the binary?

**Comment by ivarg** [comment]
Yes, when testing I just `go install` both `dlv` and my test programs.

**Comment by aarzilli** [comment]
As far as I can tell this is not unsafe anymore.
