### ISSUE TITLE
Cannot build for MacOS 

### ISSUE THREAD

**Issue by Mirodil** [derekparker/delve#971]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 
latest master
2. What version of Go are you using? (`go version`)?
1.9
3. What operating system and processor architecture are you using?
OS X EL Capitan version 10.11.6
4. What did you do?
```
$ git clone https://github.com/derekparker/delve.git
$ cd delve
$ make install
```
5. What did you expect to see?
successfully build and install
6. What did you see instead?
```
scripts/gencert.sh || (echo "An error occurred when generating and installing a new certicate"; exit 1)
go install -ldflags="-s -X main.Build=2c0e31160de8cba2a4351dcf39486d05313b4da1" github.com/derekparker/delve/cmd/dlv
codesign -s "dlv-cert"  /bin/dlv
/bin/dlv: No such file or directory
make: *** [install] Error 1
```
I do see the certificate called `dlv-cert` in my keychain.

**Comment by justinclift** [comment]
Interesting.  What are your `GOPATH` and `GOBIN` environment variables set to? :smile:

**Comment by Mirodil** [comment]
I don't have `GOPATH` or `GOBIN`. I have them in form of `$PATH:/usr/local/opt/go/libexec/bin`

**Comment by justinclift** [comment]
Ahhh.  That kind of sounds like your Go environment isn't set up yet.

Is Go generally working for other things?

**Comment by Mirodil** [comment]
yes. GO is available in terminal

**Comment by justinclift** [comment]
No worries.  I think the problem is caused by the "make install" step expecting at least `GOPATH` to be set.  That's *generally* needed for a working Go environment, but it sounds like yours is working without it somehow.

As a workaround, if you set the `GOPATH` that would probably let delve compile ok.

The Go wiki has a doc with more info on setting the `GOPATH` too if that's helpful:

&nbsp; &nbsp; https://github.com/golang/go/wiki/Setting-GOPATH

**Comment by Mirodil** [comment]
Thank you, I have done and it compiled as expected

**Comment by justinclift** [comment]
You're welcome @Mirodil. :smile:
